micronaut:
  application:
    name: demo
datasources:
  default:
    url: 'jdbc:otel:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE'
    username: sa
    password: ''
    driver-class-name: io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver

otel:
  traces:
    exporter: otlp
  exporter:
    otlp:
      endpoint: http://localhost:5050
      compression: gzip
      insecure: true
      instance: ${random.shortuuid}
    experimental:
      expoter:
        otlp:
          retry:
            enabled: true
  metrics:
    exporter: none

netty:
  default:
    allocator:
      max-order: 3
